### ISSUE TITLE
AttributeError: module 'iso639' has no attribute 'languages'

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#1]
I am getting an error with iso639:

```console
$ curator tag -s audio -t language --only-macrolanguages movie.mkv
Traceback (most recent call last):
  File "/home/aorth/src/python-venvs/curator/bin/curator", line 8, in <module>
    sys.exit(main())
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 143, in main
    handler(sys.argv[2:])
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 119, in curator_tag
    plan = plan_tag(media, args.streams, args.tag, args.value, args.skip_tagged, opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/plans/tag.py", line 63, in plan_tag
    lang = task.inputs[0].detect_language(opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/stream.py", line 67, in detect_language
    return self.detect_audio_language(opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/stream.py", line 119, in detect_audio_language
    part3 = iso639.languages.get(part1=key).part3
AttributeError: module 'iso639' has no attribute 'languages'
```

I installed the Python deps from `requirements.txt` and have the correct iso639 installed:

```console
$ pip list | grep iso
iso-639                  0.4.5
```

Running on Python 3.10 on Arch Linux. Thanks!

**Comment by alanorth** [comment]
I'm on Python 3.10 so it must be this: [Importing ABC directly from collections was deprecated and will be removed in Python 3.10](https://github.com/noumar/iso639/issues/9). That was filed almost three years ago. Ouch...

I see your CI is using Python 3.7, but even that is quite old at this point (will be [unsupported after 2023-06-27 according to python.org](https://www.python.org/downloads/)). And the iso-639 package hasn't been updated since 2016. You might need to find another library for that. Depending on how you're using language codes, you might be able to use [pycountry](https://github.com/flyingcircusio/pycountry), or just import the [iso-codes](https://salsa.debian.org/iso-codes-team/iso-codes) JSON file directly as a resource in your project.

**Comment by AlexAltea** [comment]
I have tried to replicate the issue using the `python -m venv`, but everything works fine:

```sh
mkdir test
python3 -m venv test
./test/bin/pip install git+https://github.com/AlexAltea/curator.git
wget https://raw.githubusercontent.com/AlexAltea/curator/master/requirements.txt
./test/bin/pip install -r requirements.txt
./test/bin/curator tag -s audio -t language --only-macrolanguages movie.mkv
```

I use Python 3.9 (the reference to 3.7 is just because that happens to be the oldest version that could theoretically still run curator).

I've just changed `setup.py` on https://github.com/AlexAltea/curator/commit/751a8f2874a0d08e17df43a3bf9a2eb340c673d3 so that it will install all dependencies.
**Could you please try again?** Now everything should work with just:

```sh
mkdir test
python3 -m venv test
./test/bin/pip install git+https://github.com/AlexAltea/curator.git
./test/bin/curator tag -s audio -t language --only-macrolanguages movie.mkv
```

**Comment by AlexAltea** [comment]
> And the iso-639 package hasn't been updated since 2016.

This doesn't worry me particularly. The [ISO-639-3](https://en.wikipedia.org/wiki/ISO_639-3) standard was created in 2007, and nothing has changed since: the `iso-639` package is mostly just data.

(But if gives trouble maybe we could just copy the data over)

**Comment by alanorth** [comment]
Sure, the real issue seems to be the change in import behavior in Python 3.10: [Importing ABC directly from collections was deprecated and will be removed in Python 3.10](https://github.com/noumar/iso639/issues/9).

**Comment by AlexAltea** [comment]
Apologies, I missed that part. I've replaced the dependency with a more modern one. See: https://github.com/AlexAltea/curator/commit/fa530bdcb37c9615de00ae729d222fbc48b10a2e

Could you please try again? Thanks.
