### ISSUE TITLE
rich missing from setup.py and requirements.txt

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#15]
On a clean install I noticed that `rich` is not listed in the requirements. Thanks!

*Edit: oh, it seems `textual` is missing too!*

**Comment by AlexAltea** [comment]
Fixed in https://github.com/AlexAltea/curator/commit/c54a9c6681b3713c2daeb25fed84027c5401bf1c.

(And I was _so_ convinced I would never _ever_ forget about keeping `requirements.txt` and `setup.py` in sync...)
