### ISSUE TITLE
Invalid cross-device link in `curator tag`

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#3]
On my Linux media server I have an issue with `curator tag` failing due to an "Invalid cross-device link" error:

```console
$ curator tag -s audio -t language --only-macrolanguages movie.mp4 
┌───┬──────────────────┬────────┬─────────┬───┬─────────┐
│ # │ Name             │ Stream │ Old tag │ → │ New tag │
├───┼──────────────────┼────────┼─────────┼───┼─────────┤
│ 1 │ movie.mp4        │ 1      │ und     │ → │ eng     │
└───┴──────────────────┴────────┴─────────┴───┴─────────┘
Continue? [y/N] y
Traceback (most recent call last):
  File "/home/aorth/src/python-venvs/curator/bin/curator", line 8, in <module>
    sys.exit(main())
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 147, in main
    handler(sys.argv[2:])
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 124, in curator_tag
    curator_handle_plan(plan, args)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 59, in curator_handle_plan
    plan.apply()
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/plan.py", line 20, in apply
    task.apply()
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/plans/tag.py", line 37, in apply
    os.replace(output, s.media.path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp4aqs02t3/output.mp4' -> 'movie.mp4'
```

This could be because my media file is on a different file system than my `/tmp`, or because the file system is BTRFS. Not sure.

**Comment by alanorth** [comment]
It seems this is because the media files exist on separate file systems. After reading [this comment](https://stackoverflow.com/questions/11578443/trigger-io-errno-18-cross-device-link), I've successfully used `shutil.move()` instead of `os.replace()` in `curator/plans/tag.py`, though I don't know how portable that is (I only use Linux).

Maybe you could offer a command line flag or environment variable to set the temp directory, then perform the temp options relative to that. Or, create your temp directory as a sibling to the source media file:

- Source: `/srv/video/movies/My Movie (2023).mp4`
- Temp dir: `/srv/video/movies/.tmp3ehds_pt/movie.mp4`

I'm not sure which of these three options is the best. Maybe there are others...

**Comment by vertiger** [comment]
shutil is very portable, that should be used
and the temp file should be put beside the original file so shutil can do a move on the same filesystem

**Comment by alanorth** [comment]
Another reason to not use `/tmp` would be due to file size:

```console
$ curator tag -s audio -t language movie.mkv
...
av_interleaved_write_frame(): No space left on device
```

Indeed, this movie larger than my `/tmp`:

```console
$ ls -lh movie.mkv
-rw-r--r-- 1 aorth aorth 11G Feb 27  2020 movie.mkv
$ df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           6.8G  8.0K  6.8G   1% /tmp
```

**Comment by AlexAltea** [comment]
Apologies, I've been offline while travelling, I will push the fix now.

Yes, I should have used `shutil`, it's a terrible habit to use `os.replace`.

**Comment by AlexAltea** [comment]
Fixed in https://github.com/AlexAltea/curator/commit/a527c8703f08aa175e04203af771790b475f9ac9.

**Comment by AlexAltea** [comment]
> Another reason to not use `/tmp` would be due to file size:

~~Not sure how to address this, I think the most obvious approach would be to create a temporary directory in directory that contains the target movie... but that could pollute your movies directory if something goes wrong...~~

~~Perhaps the most sensible approach would be trying first `/tmp` (Python's *tempfile* default) and if there's not enough space, then try using the target volume that contains the movie (e.g. `/mnt/externalhdd/.tmp-curator-$random`).~~

EDIT: Agreed, actually there's performance reasons to use the same volume (avoiding writing the data twice).
Regardless of `shutil.move` usage, we should be fixing the root problem. I'll open a new issue about this.

EDIT2: Tracked at https://github.com/AlexAltea/curator/issues/5

EDIT3: Done.
